alias: Display // 1 // Time
description: ""
triggers:
  - trigger: time_pattern
    minutes: /1
mode: single
actions:
  - data:
      rgb_color:
        - 255
        - 255
        - 255
    target:
      entity_id:
        - light.matrixclock_scrolling_sign
    action: light.turn_on
  - data:
      value: "{{ states(\"sensor.time\") }}"
    target:
      entity_id: text.helper_displaytext_matrixclock
    action: text.set_value
  - data:
      value: ""
    target:
      entity_id:
        - text.helper_icon_matrixclock
    action: text.set_value
